# SwiftLint Configuration for Serendipity Planner

disabled_rules:
  - trailing_comma
  - nesting
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - empty_string
  - first_where
  - last_where
  - sorted_first_last
  - toggle_bool

excluded:
  - .build
  - DerivedData
  - Config

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

large_tuple:
  warning: 3
  error: 4

type_name:
  min_length: 3
  max_length: 50
