name: SerendipityPlanner
options:
  bundleIdPrefix: com.serendipity
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Debug.xcconfig

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: SerendipityPlanner/Info.plist

targets:
  SerendipityPlanner:
    type: application
    platform: iOS
    sources:
      - path: SerendipityPlanner
        excludes:
          - "**/.DS_Store"
      - path: SerendipityWidget/SharedDataManager.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.serendipity.planner
        INFOPLIST_FILE: SerendipityPlanner/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
    entitlements:
      path: SerendipityPlanner/SerendipityPlanner.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.serendipity.planner
    dependencies:
      - target: SerendipityWidgetExtension
        embed: true

  SerendipityWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: SerendipityWidget
        excludes:
          - "**/.DS_Store"
      - path: SerendipityPlanner/Models/Suggestion.swift
      - path: SerendipityPlanner/Models/FreeTimeSlot.swift
      - path: SerendipityPlanner/Models/WeatherData.swift
      - path: SerendipityPlanner/Views/Home/SkyGradientView.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.serendipity.planner.widget
        INFOPLIST_FILE: SerendipityWidget/Info.plist
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    entitlements:
      path: SerendipityWidget/SerendipityWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.serendipity.planner

  SerendipityPlannerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SerendipityPlannerTests
    dependencies:
      - target: SerendipityPlanner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.serendipity.planner.tests
