name: Auto Assign PR

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR creator
        run: gh pr edit "$PR_URL" --add-assignee "$PR_AUTHOR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
